### ISSUE TITLE
[FR] OPDS backend

### ISSUE THREAD

**Issue by ildar** [FunkyMuse/Aurora#27]
like the app UI and functionality. Yet Library Genesis doesn't cover all books of my interest.
It would be great to have Aurora work with OPDS catalogues.

**Comment by FunkyMuse** [comment]
What's OPDS?

**Comment by ildar** [comment]
The Open Publication Distribution System specification is prepared by an
informal grouping of partners, combining Internet Archive
<https://en.wikipedia.org/wiki/Internet_Archive>, O'Reilly Media
<https://en.wikipedia.org/wiki/O%27Reilly_Media>, Feedbooks
<https://en.wikipedia.org/wiki/Feedbooks>, OLPC
<https://en.wikipedia.org/wiki/One_Laptop_per_Child>, and others. (
https://en.wikipedia.org/wiki/Open_Publication_Distribution_System)
In practice many e-book readers use it for downloading books from the app.
So this is a quite popular format for online libraries. Example apps:
CoolReader, KOReader, FBReader.

**Comment by FunkyMuse** [comment]
This application is targeting Libgen, it's totally different than the ones you've mentioned.
