### ISSUE TITLE
Need help in Converting build.gradle to build.gradle.kts

### ISSUE THREAD

**Issue by prdp89** [FunkyMuse/Aurora#30]
Hi,

I am trying to convert your [Project/Top level](https://github.com/FunkyMuse/Aurora/blob/main/build.gradle) gradle to kts-dsl but didn't get much success.

In the same file at line #102 it is unable to find **project.android** {}. Could you help in this?

Thanks.

**Comment by FunkyMuse** [comment]
Hi, you can open a PR and i can help, thanks
