### ISSUE TITLE
[Feature request]: add the possibility to filter search results by language

### ISSUE THREAD

**Issue by darhma** [FunkyMuse/Aurora#45]
As I said in the title, I think it would be useful to add the possibility of filtering search results according to language (for example, in the case of a search by author that will probably return results of books published in different languages).

**Comment by FunkyMuse** [comment]
I don't think this is possible from Libgen

**Comment by darhma** [comment]
Ok it would be a handy feature, but if it can't be implemented I don't think it's a big problem. I made the request because using a lot the search by author function I noticed the impossibility to select the language filter that can be selected as a search field, so as a workaround I'll do the search by authors separately (on a browser) and then once I find the title in the desired language I'll do the search by title so I should find the book directly in the right language.

**Comment by FunkyMuse** [comment]
After looking into this, it's impossible, due to limitations from Libgen itself.
