### ISSUE TITLE
Download Not Working

### ISSUE THREAD

**Issue by scientiac** [FunkyMuse/Aurora#70]
I tried to download many books but none of them were downloaded via the app, it says that the download is failed. But pasting  the clipboard link works. 

And when I checked the setting it didn't have any toggle to enable Storage Permission. How would it store the book?

![Screenshot_20211111-200949_Permission_controller](https://user-images.githubusercontent.com/58177655/141314418-5078c803-fc12-4ed9-bf66-14094222bf23.png)

**Comment by FunkyMuse** [comment]
It's not app's problem it's the servers from Libgen
